[package]
name = "kola-span"
version = "0.1.0"
edition = "2024"

[dependencies]
kola-utils.workspace = true
kola-interner.workspace = true
camino.workspace = true
derive_more.workspace = true
owo-colors.workspace = true
ariadne = { version = "0.6", features = ["concolor"] }
pathdiff = { version = "0.2.3", features = ["camino"] }
