[package]
name = "kola-tree"
version = "0.1.0"
edition = "2024"

[dependencies]
kola-tree-macro = { path = "./macro" }
kola-subst.workspace = true
kola-interner.workspace = true
kola-print.workspace = true
serde.workspace = true
derive_more.workspace = true
pastey.workspace = true
enum-as-inner.workspace = true
kinded.workspace = true
indexmap.workspace = true
